string sampler_type
int32 num_samples
geometry_msgs/Point center
float32 radius
float32 length
float32 min_theta
float32 max_theta
float32 delta_yaw
float32 delta_pitch
---
geometry_msgs/PoseArray view_samples